# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gke_databases_postgres_chaos_testing_06_pod_memory_hog_engine]
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pod-memory-chaos
  namespace: postgres
spec:
  # It can be active/stop
  engineState: 'active'
  appinfo:
    appns: "postgres"
    applabel: "application=spilo"
    appkind: "statefulset"
  chaosServiceAccount: pod-memory-hog-exec-sa
  experiments:
    - name: pod-memory-hog-exec
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '600' # in seconds

            # Enter the amount of memory in megabytes to be consumed by the application pod
            - name: MEMORY_CONSUMPTION
              value: '500'

            ## percentage of total pods to target
            - name: PODS_AFFECTED_PERC
              value: '66'
            - name: TARGET_PODS
              value: "my-cluster-0,my-cluster-1,my-cluster-2"
# [END gke_databases_postgres_chaos_testing_06_pod_memory_hog_engine]
