# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: v1
kind: Pod
metadata:
  name: kafkaclient
spec:
  containers:
  - name: kafkaclient
    image: quay.io/strimzi/kafka:0.35.0-kafka-3.6.0 
    command: ["sh", "-c", "exec tail -f /dev/null"]
    env:
    - name: OAUTH_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          name: oauth-access-token
          key: accesstoken
    volumeMounts:
    - name: config-volume
      mountPath: /tmp/oauth
  volumes:
  - name: config-volume
    configMap:
      name: oauth-client-properties
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-client-properties
data:
  client.properties: |
   security.protocol=SASL_PLAINTEXT
   sasl.mechanism=OAUTHBEARER
   sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required oauth.token.endpoint.uri="https://oauth2.googleapis.com/token" oauth.username.claim="email";
   sasl.login.callback.handler.class=io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
 
