# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START gke_databases_postgres_chaos_testing_01_postgres_psql_client]
apiVersion: v1
kind: Pod
metadata:
  name: psql
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: "app.stateful/component"
            operator: NotIn
            values:
            - "postgres-operator"
  tolerations:
  - key: "app.stateful/component"
    operator: "Equal"
    value: "postgres-operator"
    effect: NoSchedule
  containers:
  - name: main
    image: postgres:15
    command: ["sleep", "360000"]
    env:
    - name: PGHOST
      value: my-cluster
    - name: PGPORT
      value: "5432"
    - name: PGDATABASE
      value: mydatabase
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          name: mydatabaseowner.my-cluster.credentials.postgresql.acid.zalan.do
          key: username
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: mydatabaseowner.my-cluster.credentials.postgresql.acid.zalan.do
          key: password
    resources:
      requests:
        cpu: 1000m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 1Gi
# [END gke_databases_postgres_chaos_testing_01_postgres_psql_client]